#!/usr/bin/env python3
"""
png2asm.py
Convert 10x8 B/W PNGs to assembly bytes (one byte per row).
Usage: python3 png2asm.py input_folder [output.asm]
Requires: Pillow (pip install pillow)
"""
import sys, os, re
from PIL import Image

def sanitize_label(name):
    name = re.sub(r'^\s*\d*_*', '', name)
    name = re.sub(r'[^0-9A-Za-z_]', '_', name)
    if re.match(r'^[0-9]', name):
        name = '_' + name
    return name

def pixel_is_black(px):
    if isinstance(px, int):
        return px < 128
    if len(px) >= 3:
        r, g, b = px[0], px[1], px[2]
        lum = 0.299*r + 0.587*g + 0.114*b
        return lum < 128
    return False

def process_image(path):
    im = Image.open(path).convert('RGBA')
    w, h = im.size
    if (w, h) != (10, 8):
        raise ValueError(f"{os.path.basename(path)}: expected 10x8, got {w}x{h}")
    rows = []
    for y in range(8):
        val = 0
        for x in range(w):
            px = im.getpixel((x, y))
            if pixel_is_black(px):
                val |= (1 << (15-x))
        rows.append(val)
    return rows

def split_rows(rows, offset):
    out = []
    overflow = []
    for r in rows:
        out.append(r>>(8+offset))
        overflow.append((r>>offset)&0xff)
    out += overflow
    return out

def format_byte(b):
    return f"%{b:08b}"

from pprint import pprint
def main(inp_folder, out_file):
    pngs = sorted(f for f in os.listdir(inp_folder) if f.lower().endswith('.png'))
    pprint(pngs)
    if not pngs:
        print("No PNG files found.")
        return
    with open(out_file, 'w', encoding='utf-8') as out:
        out.write("; Generated by png2asm.py\n\n;Indexes:\n")
        for tile_index, fname in enumerate(pngs):
            label = sanitize_label(os.path.splitext(fname)[0])
            out.write(f"{label}_Index = {tile_index}\n")
        count = 0
        for offset in range(0, 7, 2):
            out.write(";---------------------------------------\n")
            out.write(f"; offset = {offset}\n")
            for tile_index, fname in enumerate(pngs):
                label = sanitize_label(os.path.splitext(fname)[0])
                count += 1
                rows = process_image(os.path.join(inp_folder, fname))
                rows = split_rows(rows, offset)
                out.write(";---------------------------------------\n")
                out.write(f";{label}\n")
                for b in rows:
                    out.write(f"    !byte {format_byte(b)}\n")
                out.write("\n")
    print(f"Wrote {count} tiles to {out_file}")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: png2asm.py input_folder [output.asm]")
        sys.exit(1)
    inp = sys.argv[1]
    outp = sys.argv[2] if len(sys.argv) > 2 else "tiles.asm"
    main(inp, outp)
